// auth_service.dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'app_routes.dart';

class AuthService {
  // Get instances of Firebase Auth and Firestore
  final FirebaseAuth _firebaseAuth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  /// Creates a new user with email/password and saves their
  /// data to a 'users' collection in Firestore.
  Future<void> registerAndSaveUser(
    String email,
    String password,
    String name,
    String userType, // This will be 'student' or 'instructor'
    String roleSpecificData, // This will be the studentId or department
    Map<String, dynamic>? extraFields,
  ) async {
    try {
      // --- STEP 1: Create the User in Firebase Authentication ---
      // This handles the email/password login part
      UserCredential userCredential =
          await _firebaseAuth.createUserWithEmailAndPassword(
        email: email,
        password: password,
      );

      // Get the unique user ID (uid) generated by Firebase Auth
      String uid = userCredential.user!.uid;

      // --- STEP 2: Prepare the Data to Save to Firestore ---
      // Create a 'map' (like a dictionary) of the user's data
      Map<String, dynamic> userData = {
        'uid': uid,
        'name': name,
        'email': email,
        'userType': userType,
        'createdAt': FieldValue.serverTimestamp(), // Adds a server timestamp
      };

      // Add the specific data based on the user's role
      if (userType == 'student') {
        userData['studentId'] = roleSpecificData;
      } else if (userType == 'instructor') {
        userData['department'] = roleSpecificData;
      }

      // Merge any additional fields provided by the caller
      if (extraFields != null && extraFields.isNotEmpty) {
        userData.addAll(extraFields);
      }

      // --- STEP 3: Save the Data to Firestore ---
      // 1. Go to the 'users' collection
      // 2. Create a new document using the user's 'uid' as the ID
      // 3. Set the data for that document using the map we created
      await _firestore.collection('users').doc(uid).set(userData);

    } on FirebaseAuthException catch (e) {
      // Re-throw the error so the UI can catch it and show a SnackBar
      throw Exception(e.message);
    } catch (e) {
      throw Exception('An unknown error occurred: $e');
    }
  }

  /// Logs in a user and navigates to the appropriate page based on their role.
  Future<void> loginUser(String email, String password, Function(String route) navigate) async {
    try {
      // Sign in the user with Firebase Authentication
      UserCredential userCredential =
          await _firebaseAuth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );

      // Get the user's UID
      String uid = userCredential.user!.uid;

      // Fetch the user's data from Firestore
      DocumentSnapshot userDoc =
          await _firestore.collection('users').doc(uid).get();

      if (userDoc.exists) {
        Map<String, dynamic> userData =
            userDoc.data() as Map<String, dynamic>;

        // Navigate based on the userType
        if (userData['userType'] == 'admin') {
          navigate(AppRoutes.adminPage);
        } else if (userData['userType'] == 'instructor') {
          navigate(AppRoutes.instructorHome);
        } else if (userData['userType'] == 'student') {
          navigate(AppRoutes.studentHome);
        } else {
          throw Exception('Unknown user type');
        }
      } else {
        throw Exception('User data not found');
      }
    } on FirebaseAuthException catch (e) {
      throw Exception(e.message);
    } catch (e) {
      throw Exception('An unknown error occurred: $e');
    }
  }
}