// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4UWmSZNGIVfFrvTzL74R_B0-0NWNzze8',
    appId: '1:209814555296:web:0d29d7f8dffe76df76d7c5',
    messagingSenderId: '209814555296',
    projectId: 'facts-app-bd7ef',
    authDomain: 'facts-app-bd7ef.firebaseapp.com',
    storageBucket: 'facts-app-bd7ef.firebasestorage.app',
    measurementId: 'G-06575HWB3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmDX7RG5VYnRiLKvFNNNkXxu2XlXzVJPQ',
    appId: '1:209814555296:android:4ac68426bfd66e2076d7c5',
    messagingSenderId: '209814555296',
    projectId: 'facts-app-bd7ef',
    storageBucket: 'facts-app-bd7ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDianCjVPXMn__V6CHamVczV11NhBwlP3U',
    appId: '1:209814555296:ios:176085cbf32e19ee76d7c5',
    messagingSenderId: '209814555296',
    projectId: 'facts-app-bd7ef',
    storageBucket: 'facts-app-bd7ef.firebasestorage.app',
    iosBundleId: 'com.example.factsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDianCjVPXMn__V6CHamVczV11NhBwlP3U',
    appId: '1:209814555296:ios:176085cbf32e19ee76d7c5',
    messagingSenderId: '209814555296',
    projectId: 'facts-app-bd7ef',
    storageBucket: 'facts-app-bd7ef.firebasestorage.app',
    iosBundleId: 'com.example.factsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4UWmSZNGIVfFrvTzL74R_B0-0NWNzze8',
    appId: '1:209814555296:web:3470454a8431b5cc76d7c5',
    messagingSenderId: '209814555296',
    projectId: 'facts-app-bd7ef',
    authDomain: 'facts-app-bd7ef.firebaseapp.com',
    storageBucket: 'facts-app-bd7ef.firebasestorage.app',
    measurementId: 'G-9TSHGBDJ28',
  );
}
