// main.dart
import 'package:flutter/material.dart';
import 'login.dart';
import 'homepage_instructor.dart';
import 'homepage_student.dart';
import 'admin_page.dart';
import 'app_routes.dart';
import 'user_type_selector_page.dart';
import 'student_register_page.dart';
import 'instructor_register_page.dart';
import 'face_scan_page.dart';
import 'classconfig.dart';
import 'class_details_page.dart';
import 'upload_class_list.dart';
import 'package:firebase_core/firebase_core.dart'; // 1. Import Firebase Core
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // 2. Import the options file (GENERATED BY flutterfire configure)

void main() async { // 3. Make main async
  WidgetsFlutterBinding.ensureInitialized(); // 4. Add this line
  await Firebase.initializeApp( // 5. Initialize Firebase
    options: DefaultFirebaseOptions.currentPlatform,
  );
  // Enable Firestore offline persistence to reduce repeated network reads
  try {
    FirebaseFirestore.instance.settings = const Settings(persistenceEnabled: true);
  } catch (_) {
    // If settings cannot be applied (platform-specific), ignore silently.
  }
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'F.A.C.T.S',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      initialRoute: AppRoutes.login,
      routes: {
        AppRoutes.login: (ctx) => const LoginPage(),
        AppRoutes.instructorHome: (ctx) => const HomePage(),
        AppRoutes.studentHome: (ctx) => const StudentHomePage(),
        AppRoutes.adminPage: (ctx) => const AdminPage(),
        AppRoutes.userTypeSelector: (ctx) => const UserTypeSelectorPage(),
        AppRoutes.studentRegister: (ctx) => StudentRegisterPage(),
        AppRoutes.instructorRegister: (ctx) => const InstructorRegisterPage(),
      },
      onGenerateRoute: (settings) {
        switch (settings.name) {
          case AppRoutes.faceScan:
            final userIdentifier = settings.arguments as String?;
            return MaterialPageRoute(builder: (_) => FaceScanPage(userIdentifier: userIdentifier ?? ''));
          case AppRoutes.classConfig:
            return MaterialPageRoute(builder: (_) => const ClassConfigPage());
          case AppRoutes.classDetails:
            final args = settings.arguments as ClassInfo?;
            return MaterialPageRoute(builder: (_) => ClassDetailsPage(classInfo: args!));
          case AppRoutes.uploadClassList:
            final args = settings.arguments as ClassInfo?;
            return MaterialPageRoute(builder: (_) => UploadClassListPage(classInfo: args!));
          default:
            return null;
        }
      },
    );
  }
}