// main.dart
import 'package:flutter/material.dart';
import 'login.dart';
import 'package:firebase_core/firebase_core.dart'; // 1. Import Firebase Core
import 'firebase_options.dart'; // 2. Import the options file (GENERATED BY flutterfire configure)

void main() async { // 3. Make main async
  WidgetsFlutterBinding.ensureInitialized(); // 4. Add this line
  await Firebase.initializeApp( // 5. Initialize Firebase
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'F.A.C.T.S',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: LoginPage(),
    );
  }
}